### PR TITLE
add disconnect

### PR DESCRIPTION
**Pull request by billfreeman44**

### CODE REVIEW

**Review by razor-x — CHANGES_REQUESTED** [review]
1. I think it's safe to drop `analysis`, so the full path can be `notebooks/player_disconnect/Disconnect reason.ipynb`
2. If the attribution is going to use a color, let's use our colors. So for green background + text, it should look like the buttons on the site. It's also weird that that plot colors match the attribution. Really, just try making the attribution plain black (or the dark background color we use on the site). If we have a color or other style I expect we will end up with lots of variations on this, which is not good for brand consistency.
3. Ideally the color scheme would match the dark background style we use on the site for our current plots, and the attribution would be our logo. But I understand we also want an example for contributors to use that would work with any other style, hence keeping the attribution dead simple.

**Comment by billfreeman44** [comment]
I think just calling it `player_disconnect` is a bit confusing, because it exactly matches the channel name. It also isn't descriptive.

For the colors, I made them the same as the green in the logo, but I can switch to the buttons. Maybe the plot colors can be whatever and the attribution can be our green to match.

For point #3, we can make a plot wrapper at some point that does this.

**Comment by billfreeman44** [comment]
I'm gonna match the bar colors to the red (disconnect = bad, duh) and the button from webapp

```
try_again_red = "#cf6262"
button_green = "#53ac67"
```

**Comment by billfreeman44** [comment]
download

this what the attribution looks like with exact button colors

**Comment by billfreeman44** [comment]
download


with the text color as the background

**Comment by billfreeman44** [comment]
download

plain black, with a box

**Comment by billfreeman44** [comment]
I'm gonna go w/ that one i think

**Comment by razor-x** [comment]
How about just no box 🤞🏻

**Comment by billfreeman44** [comment]
> 
download

**Pull request merged**
